name: Flutter CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
            flutter-version: '3.27.2'
            cache: true
            cache-key: flutter
            cache-path: ${{ github.workspace }}/flutter
            channel: 'stable'



      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
